from pathlib import Path
import json
from bem import Solution
from generate import fieldmap,trace
from provenance import load_dataset,read_checkpoint,parameter_hash

R=Path(__file__).resolve().parents[1]


def main():
    d=load_dataset(R)
    expected=parameter_hash(R)
    # Check both artifacts before running field solves or modifying any output.
    d['checks3d']=read_checkpoint(R/'qa/finite-width-3d.json',expected)
    d['checksFVM']=read_checkpoint(R/'qa/independent-fvm.json',expected)
    d['erFields']={}
    for row in d['er_scan']:
        er=row['er'];s=Solution(0,er,n=128);paths,ends=trace(s)
        d['erFields'][str(er)]={'theta_deg':0,'paths_m':paths,'path_ends':ends,**fieldmap(s)}
        print('er field',er,flush=True)
    d['provenance']['finiteWidth3DValidated']='Air-only convergence checkpoints at 0,90,180 degrees; not a whole-curve or dielectric 3D validation'
    d['provenance']['fvmIndependence']='Separate finite-volume discretization. Air outer boundary is zero; dielectric outer potential uses the 2D BEM n=96 neutral reference.'
    d['provenance']['checkpointParameterSha256']=expected
    text=json.dumps(d,separators=(',',':'))
    (R/'data/results.json').write_text(text,encoding='utf-8')
    (R/'source/src/physics/data.ts').write_text('/* Generated by the SI-parameter electrostatic solvers in physics/. Do not edit numerical arrays. */\nexport const DATA:any = '+text+';\n',encoding='utf-8')


if __name__=='__main__':main()
