"""Actual DOM/keyboard integration checks. Software assertions, not material validation."""
from harness import *
import json,hashlib,sys
folder=ROOT/'qa/interactions';folder.mkdir(parents=True,exist_ok=True)
sha=hashlib.sha256((ROOT/'dist/ProxiTouch-offline.html').read_bytes()).hexdigest()
records=[]
with sync_playwright() as p:
 b,page,errors=launch(p);page.set_default_timeout(10000)
 try:
  page.evaluate("window.__PT.quality('safe')")
  def check(name,condition,detail=None):
   rec={'name':name,'passed':bool(condition),'detail':detail};records.append(rec)
   print('PASS' if condition else 'FAIL',name,flush=True)
   (folder/'report.json').write_text(json.dumps({'sourceSha256':sha,'quality':'safe','browserErrors':errors,'checks':records},ensure_ascii=False,indent=2))
  def snap():return page.evaluate('window.__PT.snapshot()')
  def diag():return page.evaluate('window.__PT.diagnostics()')
  check('23 scenes exposed',page.evaluate('window.__PT.scenes.length')==23)
  check('Default formal body visible',page.locator('.copy-scroll').is_visible())
  page.evaluate("window.__PT.app.goTo('S06',0,true)")
  check('Book animation was playing before keyboard finish',snap()['playing'])
  page.keyboard.press('ArrowRight');s=snap();check('First Right finishes current entire animation',s['scene']=='S06' and s['phase']==1 and not s['playing'],s)
  page.keyboard.press('ArrowRight');s=snap();check('Second Right advances next scene',s['scene']=='S07',s)
  page.evaluate("window.__PT.app.goTo('S09',0,true)")
  check('EDL was playing before button finish',snap()['playing'])
  page.locator('#next-button').click();s=snap();check('Next button finishes current animation',s['scene']=='S09' and s['phase']==1,s)
  page.locator('#next-button').click();s=snap();check('Second Next button advances',s['scene']=='S10',s)
  page.evaluate("window.__PT.app.goTo('S16',.2,true)");page.keyboard.press('ArrowLeft');s=snap();check('Back gives prior scene stable end',s['scene']=='S15' and s['phase']==1 and not s['playing'],s)
  page.keyboard.press('t');check('T collapses body',not page.locator('.copy-scroll').is_visible())
  page.locator('.explanation-heading').click();check('Body heading re-expands explanation',page.locator('.copy-scroll').is_visible())
  page.evaluate("window.__PT.goTo('S19',.35)")
  region=page.locator('.copy-scroll').bounding_box();page.mouse.move(region['x']+region['width']*.5,region['y']+region['height']*.6);page.mouse.wheel(0,1000);page.wait_for_function("document.querySelector('.copy-scroll').scrollTop>0",timeout=10000)
  scroll=page.locator('.copy-scroll').evaluate('(e)=>e.scrollTop');check('Formal body scrolls independently',scroll>0,{'scrollTop':scroll,'diagnostic':diag()})
  before=snap();page.keyboard.press('e');check('E enters Explore',snap()['mode']=='explore')
  page.locator('[data-view="micro"]').click();page.locator('#depth-input').fill('0.7');page.locator('#depth-input').dispatch_event('input')
  check('Explore depth drives model',abs(snap()['model']['depth']-.7)<1e-8)
  page.keyboard.press('Escape');after=snap();scroll2=page.locator('.copy-scroll').evaluate('(e)=>e.scrollTop')
  check('Escape restores presentation scene, state and camera',all(before[k]==after[k] for k in ['scene','phase','model','camera','notes']),{'before':before,'after':after})
  check('Explore return preserves body scroll',abs(scroll2-scroll)<1,{'before':scroll,'after':scroll2})
  page.keyboard.press('g');check('G opens actual chapter menu',page.locator('.chapter-menu').is_visible())
  check('Chapter menu contains 23 scene buttons',page.locator('.chapter-group button').count()==23)
  page.locator('.chapter-group button').nth(14).click();check('Actual chapter selection goes to S14',snap()['scene']=='S14');page.keyboard.press('ArrowRight')
  page.locator('#about-button').click();check('About panel opens',page.locator('.about').is_visible());page.keyboard.press('Escape');check('Escape closes About',not page.locator('.about').is_visible())
  for first,second in [('S15','S16'),('S16','S17')]:
   page.evaluate('s=>window.__PT.goTo(s,1)',first);a=snap();page.evaluate('s=>window.__PT.goTo(s,0)',second);c=snap();
   check(first+' -> '+second+' mechanical continuity',a['model']['interaction']==c['model']['interaction'])
   check(first+' -> '+second+' fitted camera continuity',a['camera']==c['camera'],{'a':a['camera'],'b':c['camera']})
  page.evaluate("window.__PT.goTo('S01',1)");page.keyboard.press('e');page.locator('[data-view="device"]').click();check('Device Explore not locked before Design',snap()['view']=='device')
  page.locator('[data-view="exploded"]').click();check('Exploded Explore not locked before Design',snap()['view']=='exploded');page.keyboard.press('Escape')
  page.keyboard.press('Home');check('Home opens cover',snap()['scene']=='S00');page.keyboard.press('End');check('End opens final',snap()['scene']=='S22')
  check('Final Next button is disabled',page.locator('#next-button').is_disabled())
  page.screenshot(path=str(folder/'ending-after-controls.png'))
  check('No console/JS errors',not errors,errors)
  check('No GL, layout, label or formula errors',diag()['glError']==0 and not diag()['overflow'] and not diag()['labelOverlapCount'] and not diag()['mathErrors'],diag())
 finally:b.close()
if any(not r['passed'] for r in records):sys.exit(1)
