import assert from 'node:assert/strict';
import { SCENES,scenePatch } from '../../dist/js/scenes/definitions.js';
import { COPY } from '../../dist/js/scenes/copy.js';
import { interaction } from '../../dist/js/physics/interaction.js';
import { MicroAssembly } from '../../dist/js/models/Dome.js';
import { Device } from '../../dist/js/models/Device.js';
import { FringeField } from '../../dist/js/models/FringeField.js';
import { SharedArray } from '../../dist/js/models/SharedArray.js';
import { revisionFieldData } from '../../dist/js/physics/revisionFieldData.js';
import {CLASSIC_POSITIONS} from '../../dist/js/worlds/WorldManager.js';
import {mutualPlotLimit} from '../../dist/js/ui/Plots.js';
import {mutualSignal} from '../../dist/js/models/FringeField.js';
import fs from 'node:fs';
const tests=[];function test(name,fn){fn();tests.push({name,passed:true});console.log('PASS',name);}
const near=(a,b,tol=1e-6)=>assert.ok(Math.abs(a-b)<tol,`${a} != ${b}`);
test('23 knowledge-unit scenes; 0/11/8/3 structure',()=>{assert.equal(SCENES.length,23);assert.equal(SCENES.filter(x=>x.part==='I').length,11);assert.equal(SCENES.filter(x=>x.part==='II').length,8);assert.equal(SCENES.filter(x=>x.part==='III').length,3);});
test('Exact imported titles and formal body for all scenes',()=>{SCENES.forEach(s=>{assert.equal(s.title,COPY[s.id].title);assert.equal(s.body,COPY[s.id].body);});});
test('Only one complete EDL migration in the mainline',()=>{assert.deepEqual(SCENES.filter(x=>x.world==='edl').map(x=>x.id),['S09']);assert.equal(scenePatch(SCENES[10],0).bias,1);});
test('Pressure response is monotonic and includes overlap',()=>{let last=-1;for(let i=0;i<=100;i++){const a=interaction(i/100);assert.ok(a.cb>=last);last=a.cb;assert.ok(a.hc>0);}assert.ok(interaction(-.6).cb>0);assert.equal(interaction(-.05).contact,false);assert.equal(interaction(.025).contact,true);});
const micro=new MicroAssembly();
test('Nine dome contact areas equal the common state model',()=>{for(const d of [-1,-.1,-.01,0,.025,.1,.5,1]){micro.set(d);const m=interaction(d);near(micro.area,m.area,2e-6);micro.patches.forEach((p,i)=>{if(p.visible)near(p.position[1],micro.planeY+.006,2e-6);});}});
test('EC rim stays fixed; interior deforms instead of global scaling',()=>{micro.set(1);assert.equal(micro.electrode.scale[1],1);assert.ok(micro.electrodeGeometry.amount>.5);const g=micro.electrodeGeometry;near(g.weight(0,0),1);near(g.weight(g.half,0),0);assert.ok(micro.geometries[0].contactRadius>0);});
const device=new Device();
test('The HC and CB windows share the exact same EC node',()=>{assert.equal(device.channelNodes.HC[1],device.channelNodes.CB[0]);assert.equal(device.rails.length,4);assert.equal(device.core.domes.length,9);device.set(.35,.38,.8,'muxHC');assert.equal(device.activeWindow,'HC');device.set(.35,.38,.8,'muxCB');assert.equal(device.activeWindow,'CB');assert.equal(device.field.visible,false);assert.equal(device.readout.visible,true);});
test('Approach -> Touch -> Pressure state and camera continuity',()=>{for(const [a,b] of [[15,16],[16,17]]){const x=scenePatch(SCENES[a],1),y=scenePatch(SCENES[b],0);near(x.depth,y.depth);near(x.field,y.field);assert.deepEqual(SCENES[a].camera[1]||SCENES[a].camera[0],SCENES[b].camera[0]);}});
const fringe=new FringeField();
test('Book motion is monotonic, one fixed-axis half-turn, with no slide track',()=>{let angle=0;for(let i=0;i<=40;i++){fringe.set(i/40,0);assert.deepEqual(fringe.pivot.position,[0,1,0]);assert.deepEqual(fringe.rx.position,[-1.85,.85,0]);assert.ok(fringe.pivot.rotation[2]<=angle+1e-9);angle=fringe.pivot.rotation[2];}near(angle,-Math.PI);});
test('Representative finite-volume Laplace residuals are small',()=>{for(const group of ['morph','approach','square'])for(const s of revisionFieldData[group]){assert.ok(s.residual<1e-10);assert.ok(Number.isFinite(s.coupling));}assert.ok(revisionFieldData.approach.at(-1).referenceCapacitance>0);});
const array=new SharedArray();
test('4x4 has 40 unique edges, 24 shared interiors, 4 locally selected edges',()=>{array.set(16,-1,1,6);const d=array.diagnostics();assert.equal(d.pixels,16);assert.equal(d.uniqueBoundarySegments,40);assert.equal(d.sharedEdges,24);assert.equal(d.selectedEdgeCount,4);assert.equal(d.independentFramesVisible,false);assert.equal(d.wholeGridShorted,false);});
test('Scan addresses change without shorting all boundary segments',()=>{const seen=new Set();for(let i=0;i<16;i++){array.set(16,-1,1,i);assert.equal(array.selectedEdges.length,4);seen.add(array.selectedEdges.join(','));}assert.equal(seen.size,16);});
test('Three classical examples have separate 3-D envelopes',()=>{const half=4.8*.8/2;const a=CLASSIC_POSITIONS.map(p=>p[0]);assert.ok((a[1]-half)-(a[0]+half)>1);assert.ok((a[2]-half)-(a[1]+(1-.55)*4.8*.8+half)>1);});
test('Mutual chart fits the actual normalized signal without rescaling data',()=>{const ymax=mutualPlotLimit();assert.ok(ymax>0&&ymax<1);for(let i=0;i<=1000;i++){const value=mutualSignal(i/1000);assert.ok(value>=0&&value<=ymax);}});
test('Surface distribution mode does not activate nonexistent outer neighbors',()=>{array.set(16,.85,1,-1,.7,true);assert.equal(array.selectedEdges.length,0);assert.equal(array.selected,-1);});
fs.mkdirSync('../qa',{recursive:true});fs.writeFileSync('../qa/model-tests.json',JSON.stringify({testCount:tests.length,tests,scope:'Software model consistency; not physical device validation'},null,2));
