import {Renderer} from './engine/renderer.js';
import {CameraRig,CameraState} from './engine/camera.js';
import {Node,Mesh,Material,mesh} from './engine/scene.js';
import {plane} from './engine/geometry.js';
import {Vec3,clamp,smooth,normalize,cross} from './engine/math.js';
import {Experiment} from './models/Experiment.js';
import {Wedge} from './models/Wedge.js';
import {ModelState,FieldMode,P,sample,topPoint,point,sectionWidth} from './physics/model.js';
import {SCENES,Scene,stateFor} from './scenes/definitions.js';
import {HUD} from './ui/HUD.js';
import {Labels} from './ui/Labels.js';
import {DATA} from './physics/data.js';
function fitCamera(base:CameraState,pts:Vec3[],rect:DOMRect):CameraState{
 let c=structuredClone(base);const rig=new CameraRig();rig.aspect=innerWidth/innerHeight;
 const desired={left:(rect.left+50)/innerWidth,right:(rect.right-65)/innerWidth,top:(rect.top+20)/innerHeight,bottom:(rect.bottom-22)/innerHeight};
 // First shrink/grow the framing, then move the camera along its own right/up axes.
 for(let k=0;k<6;k++){
  rig.set(c);const a=pts.map(p=>rig.project(p,1,1)),xs=a.map(x=>x.x),ys=a.map(x=>x.y),lo=Math.min(...xs),hi=Math.max(...xs),up=Math.min(...ys),dn=Math.max(...ys);
  const factor=Math.max((hi-lo)/(desired.right-desired.left),(dn-up)/(desired.bottom-desired.top));
  if(k<4){const f=clamp(factor,.55,2.5);c.position=c.position.map((v,i)=>c.target[i]+(v-c.target[i])*f)as Vec3;}
  rig.set(c);const b=pts.map(p=>rig.project(p,1,1));const centerX=(Math.min(...b.map(x=>x.x))+Math.max(...b.map(x=>x.x)))/2,centerY=(Math.min(...b.map(x=>x.y))+Math.max(...b.map(x=>x.y)))/2;
  const forward=normalize(c.target.map((v,i)=>v-c.position[i])as Vec3),right=normalize(cross(forward,[0,1,0])),upv=normalize(cross(right,forward)),distance=Math.hypot(...c.position.map((v,i)=>v-c.target[i])),height=2*distance*Math.tan(c.fov*Math.PI/360);
  const dx=(centerX-(desired.left+desired.right)/2)*height*rig.aspect,dy=((desired.top+desired.bottom)/2-centerY)*height;
  const offset=right.map((v,i)=>v*dx+upv[i]*dy)as Vec3;c.position=c.position.map((v,i)=>v+offset[i])as Vec3;c.target=c.target.map((v,i)=>v+offset[i])as Vec3;
 }
 return c;
}
export class Application{
 renderer:Renderer;camera=new CameraRig();world=new Node();experiment:Experiment;wedge:Wedge;hud:HUD;labels:Labels;
 index=0;phase=0;state!:ModelState;animation?:{start:number;from:number;duration:number};explore=false;fieldCycleIndex=0;saved?:{index:number;phase:number;camera:CameraState;field?:FieldMode;full:boolean;er?:number;theta?:number;fieldCycleIndex:number;playing:boolean;auto:boolean};auto=false;timer?:ReturnType<typeof setTimeout>;capture=false;dirty=true;overrideTheta?:number;overrideEr?:number;overrideField?:FieldMode;fullWidth=false;manualCamera?:CameraState;history:{id:string;phase:number;t:number}[]=[];frameTimes:number[]=[];lastFrame=0;errors:string[]=[];
 constructor(){this.renderer=new Renderer(document.querySelector<HTMLCanvasElement>('#stage')!);const ground=mesh(this.world,plane(120),new Material(0xe4ebf0,{roughness:.95,patterned:2}),[0,-.29,0]);ground.castShadow=false;this.experiment=this.world.add(new Experiment());this.wedge=this.world.add(new Wedge());this.wedge.visible=false;
 this.hud=new HUD(document.querySelector('#app')!,{next:()=>this.next(),previous:()=>this.previous(),replay:()=>this.replay(),explore:()=>this.toggleExplore(),theta:v=>this.setTheta(v),field:v=>this.setField(v as FieldMode),material:()=>this.material(),fullWidth:()=>{this.fullWidth=!this.fullWidth;this.manualCamera=undefined;this.draw()},go:id=>this.go(id,0,true),quality:q=>this.quality(q),autoplay:()=>this.autoplay(),pause:()=>this.togglePause(),log:()=>{this.hud.chart.log=!this.hud.chart.log;this.draw()}});this.labels=new Labels(document.querySelector('#app')!);
 addEventListener('resize',()=>{this.manualCamera=undefined;this.draw()});addEventListener('keydown',e=>this.key(e));addEventListener('error',e=>this.errors.push(e.message));let drag:{x:number;y:number}|undefined;const c=this.renderer.canvas;c.addEventListener('pointerdown',e=>{if(!this.explore)return;drag={x:e.clientX,y:e.clientY};c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!drag)return;this.camera.orbit(-(e.clientX-drag.x)*.0035,-(e.clientY-drag.y)*.003);this.manualCamera=structuredClone(this.camera.state);drag={x:e.clientX,y:e.clientY};this.draw()});c.addEventListener('pointerup',()=>drag=undefined);c.addEventListener('pointercancel',()=>drag=undefined);c.addEventListener('wheel',e=>{if(!this.explore)return;e.preventDefault();this.camera.zoom(e.deltaY*.0007);this.manualCamera=structuredClone(this.camera.state);this.draw()},{passive:false});
 this.go('01',0,true);requestAnimationFrame(t=>this.tick(t));}
 get scene(){return SCENES[this.index]}
 fieldCycleEnabled(scene=this.scene){return scene.kind==='plates'&&scene.id!=='09'}
 fieldCycleModes:FieldMode[]=['lines','potential','strength'];
 resetFieldCycle(){this.fieldCycleIndex=0;if(this.fieldCycleEnabled())this.overrideField=this.fieldCycleModes[0];}
 advanceFieldCycle(){if(!this.fieldCycleEnabled())return;this.fieldCycleIndex=(this.fieldCycleIndex+1)%this.fieldCycleModes.length;this.overrideField=this.fieldCycleModes[this.fieldCycleIndex];}
 derive(){const s=stateFor(this.scene,this.phase);if(this.overrideTheta!==undefined)s.theta=this.overrideTheta;if(this.overrideEr!==undefined)s.er=this.overrideEr;if(this.overrideField)s.field=this.overrideField;s.fullWidth=this.fullWidth;s.explore=this.explore;return s}
 draw(){this.state=this.derive();const s=this.state,def=this.scene;this.renderer.resize(innerWidth,innerHeight);this.hud.update(def,s,!!this.animation,this.auto,this.renderer.quality);this.hud.root.classList.toggle('capture',this.capture);this.experiment.visible=def.kind==='plates';this.wedge.visible=def.kind==='wedge';let pts:Vec3[];
 if(this.experiment.visible){this.experiment.set(s,def.id);pts=this.experiment.bounds(s);}else{this.wedge.set(this.phase);pts=this.wedge.bounds();}
 this.camera.aspect=innerWidth/innerHeight;const base:CameraState=s.fullWidth?{position:[17,13,18],target:[0,1,0],fov:34,offset:0}:def.kind==='wedge'?{position:[7,6,15],target:[2,1.4,0],fov:34,offset:0}:{position:[5.7,4.0,13.8],target:[.5,1,0],fov:34,offset:0};
 this.camera.set(this.manualCamera||fitCamera(base,pts,this.hud.zone.getBoundingClientRect()));this.renderer.frame(this.world,this.camera);this.labels.update(def.kind==='wedge'?this.wedge.annotations():this.experiment.annotations(s,def.id),this.camera,this.hud.zone.getBoundingClientRect());this.dirty=false;
 }
 record(){this.history.push({id:this.scene.id,phase:this.phase,t:performance.now()});if(this.history.length>256)this.history.splice(0,this.history.length-256)}
 tick(t:number){if(this.animation){const a=this.animation;this.phase=clamp(a.from+(1-a.from)*(t-a.start)/a.duration);if(this.phase>=1){this.record();if(this.auto){this.phase=1;this.animation=undefined;this.schedule();}else{this.advanceFieldCycle();this.phase=0;this.animation={start:t,from:0,duration:Math.max(1,this.scene.duration*1000)};}}this.dirty=true;}if(this.dirty){if(this.lastFrame){this.frameTimes.push(t-this.lastFrame);if(this.frameTimes.length>180)this.frameTimes.splice(0,this.frameTimes.length-180)}this.lastFrame=t;this.draw();}else this.lastFrame=0;requestAnimationFrame(t=>this.tick(t));}
 schedule(){this.cancelTimer();if(this.capture){this.auto=false;return}this.timer=setTimeout(()=>{this.timer=undefined;if(this.auto&&!this.capture)this.next()},650)}
 cancelTimer(){if(this.timer!==undefined)clearTimeout(this.timer);this.timer=undefined;}
 stop(){this.animation=undefined;this.auto=false;this.cancelTimer();}
 setCapture(value=true){this.capture=value;if(value)this.stop();this.draw();}
 animate(){if(this.capture){this.stop();return}this.animation={start:performance.now(),from:this.phase,duration:Math.max(1,this.scene.duration*1000*(1-this.phase))};this.dirty=true;}
 next(){if(this.explore){this.toggleExplore(false);return}this.cancelTimer();this.animation=undefined;if(this.index<SCENES.length-1){const auto=this.auto;this.go(SCENES[this.index+1].id,0,true);this.auto=auto;}else{this.phase=0;this.auto=false;this.animate();this.draw()}}
 previous(){if(this.explore)this.toggleExplore(false);this.auto=false;this.cancelTimer();this.animation=undefined;if(this.index>0)this.go(SCENES[this.index-1].id,0,true);else{this.phase=0;this.animate();this.draw()}}
 go(id:string,phase=1,play=false){if(!Number.isFinite(phase))throw new RangeError('Phase must be finite');const index=SCENES.findIndex(s=>s.id===id);if(index<0)throw Error('Unknown scene '+id);this.index=index;this.phase=clamp(phase);this.animation=undefined;this.auto=false;this.cancelTimer();this.explore=false;this.saved=undefined;this.overrideTheta=this.overrideEr=undefined;this.overrideField=undefined;this.fullWidth=false;this.manualCamera=undefined;this.resetFieldCycle();this.draw();this.record();if(play&&phase<1)this.animate();}
 seek(p:number){if(!Number.isFinite(p))throw new RangeError('Phase must be finite');this.animation=undefined;this.phase=clamp(p);this.draw()}
 replay(){if(this.explore){this.manualCamera=undefined;this.draw();return}this.overrideTheta=this.overrideEr=undefined;this.overrideField=undefined;this.resetFieldCycle();this.phase=0;this.auto=false;this.animate();this.draw()}
 toggleExplore(force?:boolean){const next=force??!this.explore;if(next===this.explore)return;if(next){this.saved={index:this.index,phase:this.phase,camera:structuredClone(this.camera.state),field:this.overrideField,full:this.fullWidth,er:this.overrideEr,theta:this.overrideTheta,fieldCycleIndex:this.fieldCycleIndex,playing:!!this.animation,auto:this.auto};this.animation=undefined;this.auto=false;this.cancelTimer();this.timer=undefined;this.explore=true;this.overrideTheta=this.state.theta;this.manualCamera=structuredClone(this.camera.state);}else{this.explore=false;if(this.saved){const saved=this.saved;this.index=saved.index;this.phase=saved.phase;this.overrideField=saved.field;this.fullWidth=saved.full;this.overrideEr=saved.er;this.overrideTheta=saved.theta;this.fieldCycleIndex=saved.fieldCycleIndex;this.manualCamera=structuredClone(saved.camera);this.auto=saved.auto;if(saved.playing)this.animate();else if(this.auto&&this.phase>=1)this.schedule();}this.saved=undefined;}this.draw()}
 setTheta(theta:number){if(!Number.isFinite(theta))throw new RangeError('Angle must be finite');if(this.scene.kind==='wedge'||this.scene.id==='10')return;if(!this.explore)this.toggleExplore(true);this.overrideTheta=clamp(theta,0,180);this.manualCamera=undefined;this.draw()}
 setField(mode:FieldMode){if(!['lines','potential','strength','off'].includes(mode))return;this.overrideField=mode;const i=this.fieldCycleModes.indexOf(mode);if(i>=0)this.fieldCycleIndex=i;this.manualCamera=undefined;this.draw()}
 material(){if(this.scene.kind==='wedge'||this.scene.id==='10')return;if(!this.explore)this.toggleExplore(true);this.overrideEr=this.state.er===1?4:1;this.draw()}
 quality(q:string){if(!['high','safe'].includes(q))return;this.renderer.quality=q;this.draw()}
 togglePause(){if(this.capture)return;this.auto=false;this.cancelTimer();if(this.explore)return;if(this.animation)this.animation=undefined;else{if(this.phase>=1)this.phase=0;this.animate();}this.draw();}
 autoplay(){if(this.capture)return;if(this.explore)this.toggleExplore(false);this.auto=!this.auto;if(this.auto){if(this.phase>=1)this.next();else if(!this.animation)this.animate()}this.draw()}
 key(e:KeyboardEvent){const k=e.key.toLowerCase(),target=e.target as Element|null;if(e.defaultPrevented||e.ctrlKey||e.altKey||e.metaKey)return;if(k!=='escape'&&target?.closest?.('input,select,textarea,button,a[href],summary,[role="button"],[contenteditable]:not([contenteditable="false"])'))return;if(e.repeat)return;if([' ','arrowright','arrowleft','home','end','escape'].includes(k))e.preventDefault();if(k===' ')this.togglePause();else if(k==='arrowright')this.next();else if(k==='arrowleft')this.previous();else if(k==='r')this.replay();else if(k==='e')this.toggleExplore();else if(k==='escape'){this.hud.close();if(this.explore)this.toggleExplore(false)}else if(k==='g')this.hud.toggle('menu');else if(k==='p')this.autoplay();else if(k==='home')this.go('01',0,true);else if(k==='end')this.go('12',0,true);else if(k==='t'){this.hud.root.classList.toggle('copy-collapsed');this.draw()}}
 snapshot(){return{scene:this.scene.id,phase:this.phase,playing:!!this.animation,explore:this.explore,state:structuredClone(this.state),camera:structuredClone(this.camera.state),sample:sample(this.state.theta,this.state.er)}}
 diagnostics(){const copy=this.hud.diagnostics();return{...this.renderer.diagnostics(),...copy,labelOverlaps:this.labels.overlap,labelOutOfBounds:this.labels.out,scene:this.scene.id,phase:this.phase,theta:this.state.theta,materialEr:this.state.er,geometry:{hinge_m:[-P.hinge_offset_m,P.initial_clear_gap_m/2],rotation:this.experiment.hinge.rotation[2],upperNear_m:topPoint(0,P.initial_clear_gap_m,0,this.state.theta).map(v=>v/150),gapFinal_m:2*P.hinge_offset_m,width_m:P.width_m,displayWidth_m:this.experiment.visibleWidth},sample:sample(this.state.theta,this.state.er),errors:this.errors,ready:true};}
}
if(typeof document!=='undefined')try{const app=new Application();Object.assign(window,{__LAB:{ready:true,app,scenes:SCENES,parameters:P,data:DATA,goTo:(id:string,p=1,play=false)=>app.go(id,p,play),seek:(p:number)=>app.seek(p),next:()=>app.next(),previous:()=>app.previous(),replay:()=>app.replay(),theta:(v:number)=>app.setTheta(v),field:(v:FieldMode)=>app.setField(v),quality:(v:string)=>app.quality(v),explore:(v?:boolean)=>app.toggleExplore(v),render:()=>app.draw(),flush:()=>app.renderer.gl.finish(),captureMode:(v=true)=>app.setCapture(v),snapshot:()=>app.snapshot(),diagnostics:()=>app.diagnostics(),stop:()=>app.stop(),version:'1.2.1-field-cycle-order'}})}catch(e){document.querySelector('#app')!.innerHTML='<div class="error"><h1>WebGL2 initialization failed</h1><pre>'+String(e)+'</pre></div>';console.error(e)}
