"""Axisymmetric Laplace teaching section for the annular Halo buses.
This does NOT resolve the 64 interdigitated fingers, the Core circuit, or cross-talk.
It is a physically motivated low-spatial-frequency field illustration, not a
simulation or validation of the proposed sensor. Geometric units are arbitrary.
"""
from pathlib import Path
import json,time,math
import numpy as np
from scipy.sparse import lil_matrix
from scipy.sparse.linalg import spsolve
from scipy.ndimage import map_coordinates
ROOT=Path(__file__).resolve().parents[2]
NR,NZ=177,155
rs=np.linspace(0,6,NR);zs=np.linspace(-.35,5.65,NZ)
dr=rs[1]-rs[0];dz=zs[1]-zs[0]
R,Z=np.meshgrid(rs,zs)
PROFILE=np.array([[0,0],[.20,.035],[.39,.14],[.54,.31],[.615,.49],[.63,.63],[.63,2.35],[.61,2.55],[.52,2.76],[.33,2.92],[0,3.]])
HEIGHTS=PROFILE[:,1]*.65;RADII=PROFILE[:,0]*2.3
TX=(R>=3.27)&(R<=3.43)&(Z>=.23)&(Z<=.31)
RX=(R>=2.53)&(R<=2.71)&(Z>=.23)&(Z<=.31)
SEEDS=[3.295,3.340,3.389,3.421]
def solve(bottom=None):
 obj=np.zeros_like(TX)
 if bottom is not None:
  yy=Z-bottom;rr=np.interp(yy,HEIGHTS,RADII)
  obj=(yy>=0)&(yy<=HEIGHTS[-1])&(R<=rr)
 fixed=TX|RX|obj;unknown=~fixed;index=np.full(R.shape,-1,int);index[unknown]=np.arange(unknown.sum())
 A=lil_matrix((unknown.sum(),unknown.sum()));b=np.zeros(unknown.sum());values=TX.astype(float)
 for j,i in zip(*np.nonzero(unknown)):
  row=index[j,i];diag=0
  radial=[(0,1,4/dr**2)] if i==0 else [(0,1,1/dr**2+1/(2*rs[i]*dr)),(0,-1,1/dr**2-1/(2*rs[i]*dr))]
  for dj,di,w in radial+[(1,0,1/dz**2),(-1,0,1/dz**2)]:
   jj,ii=j+dj,i+di
   if not(0<=jj<NZ and 0<=ii<NR):continue
   diag+=w
   if fixed[jj,ii]:b[row]+=w*values[jj,ii]
   else:A[row,index[jj,ii]]=-w
  A[row,row]=diag
 A=A.tocsr();sol=spsolve(A,b);V=values.copy();V[unknown]=sol
 EZ,ER=np.gradient(-V,dz,dr)
 def field(p):
  co=np.array([[(p[1]-zs[0])/dz],[(p[0]-rs[0])/dr]])
  return np.array([map_coordinates(ER,co,order=1,mode='nearest')[0],map_coordinates(EZ,co,order=1,mode='nearest')[0]])
 paths=[];ends=[]
 for seed in SEEDS:
  p=np.array([seed,.335]);path=[p.copy()];target='boundary'
  for k in range(1800):
   e=field(p);n=np.linalg.norm(e)
   if n<1e-8:break
   mid=p+e/n*.011;e=field(mid);n=np.linalg.norm(e)
   if n<1e-8:break
   p=p+e/n*.022;path.append(p.copy())
   ii=int(round(p[0]/dr));jj=int(round((p[1]-zs[0])/dz))
   if not(0<=jj<NZ and 0<=ii<NR):break
   if RX[jj,ii]:target='Rx';break
   if obj[jj,ii]:target='object';break
   if p[0]<.006 or p[0]>5.985 or p[1]<-.34 or p[1]>5.63:break
  path=np.array(path);arc=np.r_[0,np.cumsum(np.linalg.norm(np.diff(path,axis=0),axis=1))];v=np.linspace(0,arc[-1],56)
  paths.append(np.stack([np.interp(v,arc,path[:,0]),np.interp(v,arc,path[:,1])],1).round(5).tolist());ends.append(target)
 flux=0
 for j,i in zip(*np.nonzero(RX)):
  for dj,di,w in [(0,1,dz/dr*2*np.pi*(rs[i]+dr/2)),(0,-1,dz/dr*2*np.pi*max(0,rs[i]-dr/2)),(1,0,dr/dz*2*np.pi*rs[i]),(-1,0,dr/dz*2*np.pi*rs[i])]:
   jj,ii=j+dj,i+di
   if 0<=jj<NZ and 0<=ii<NR and not RX[jj,ii]:flux+=V[jj,ii]*w
 return {'bottom':bottom,'coupling':float(flux),'residual':float(np.max(np.abs(A@sol-b))),'paths':paths,'endpoints':ends}
start=time.time();baseline=solve();states=[]
print('baseline',baseline['coupling'],baseline['endpoints'],flush=True)
for bottom in np.linspace(5.25,.90,16):
 s=solve(float(bottom));s['proximity']=abs(s['coupling']/baseline['coupling']-1);states.append(s)
 print('bottom',round(bottom,3),'change',round(s['proximity'],4),'ends',s['endpoints'],flush=True)
meta={'model':'Axisymmetric finite-volume Laplace section of representative annular buses','grid':[NR,NZ],'baselineCouplingArbitrary':baseline['coupling'],'maxResidual':max(x['residual'] for x in states+[baseline]),'seconds':time.time()-start,'limitations':['Annular buses only: individual fingers are not resolved','Core electrode, guard dielectric contrast and cross-talk are not solved','The object is a grounded rounded conductor, not a human-body model','No dimensions, measured transfer function or full-device validation implied']}
data={'metadata':meta,'baseline':baseline,'states':states}
(ROOT/'src/physics/haloFieldData.ts').write_text('/* Generated by scripts/physics/solve_halo.py */\nexport const haloFieldData='+json.dumps(data,separators=(',',':'))+';\n')
(ROOT.parent/'qa/halo-field-solver-report.json').write_text(json.dumps(meta,indent=2))
print('DONE',meta,flush=True)
