"""Deterministic 2-D Laplace teaching model, not a validated device simulation.
Finite-volume five-point Laplacian. Unit Tx bias, grounded Rx and conductor.
Insulating outer boundaries. Three-dimensional views repeat the computed section
in separate depth slices. All dimensions are arbitrary, not manufactured mm.
"""
from pathlib import Path
import json, math, time
import numpy as np
from scipy.sparse import lil_matrix
from scipy.sparse.linalg import spsolve
from scipy.ndimage import map_coordinates
ROOT=Path(__file__).resolve().parents[2]
NX,NY=161,111
xs=np.linspace(-6,6,NX); ys=np.linspace(-.3,7.95,NY)
dx=xs[1]-xs[0];dy=ys[1]-ys[0]
X,Y=np.meshgrid(xs,ys)

def plate(cx,cy,angle):
 c,s=np.cos(angle),np.sin(angle)
 px=(X-cx)*c+(Y-cy)*s;py=-(X-cx)*s+(Y-cy)*c
 return (abs(px)<=1.7)&(abs(py)<=.10)

def setup(u=1,distance=None):
 t=np.sin(np.pi*u)
 tx=(-2.1*u,.2+.1*t,.30*t)
 rx=(2.1*u,.2+1.7*(1-u)+1.5*t,-.65*t)
 masktx=plate(*tx); maskrx=plate(*rx)
 obj=np.zeros_like(masktx)
 if distance is not None:
  bottom=.3+distance
  nearest=np.clip(Y,bottom+.63,bottom+2.35)
  obj=(X-.05)**2+(Y-nearest)**2<=.63**2
 fixed=masktx|maskrx|obj
 return tx,rx,masktx,maskrx,obj,fixed

def solve(u=1,distance=None):
 tx,rx,mt,mr,mo,fixed=setup(u,distance)
 unknown=~fixed;index=np.full(X.shape,-1,dtype=int); index[unknown]=np.arange(unknown.sum())
 A=lil_matrix((unknown.sum(),unknown.sum()));b=np.zeros(unknown.sum())
 values=mt.astype(float)
 for j,i in zip(*np.nonzero(unknown)):
  row=index[j,i];diag=0
  for dj,di,w in [(0,1,1/dx**2),(0,-1,1/dx**2),(1,0,1/dy**2),(-1,0,1/dy**2)]:
   y,x=j+dj,i+di
   if x<0 or x>=NX or y<0 or y>=NY:continue
   diag+=w
   if fixed[y,x]:b[row]+=w*values[y,x]
   else:A[row,index[y,x]]=-w
  A[row,row]=diag
 A=A.tocsr();sol=spsolve(A,b);V=values.copy();V[unknown]=sol
 residual=float(np.max(np.abs(A@sol-b)))
 EY,EX=np.gradient(-V,dy,dx)
 def field(p):
  coords=np.array([[(p[1]-ys[0])/dy],[(p[0]-xs[0])/dx]])
  return np.array([map_coordinates(EX,coords,order=1,mode='nearest')[0],map_coordinates(EY,coords,order=1,mode='nearest')[0]])
 def is_end(p):
  ii=int(round((p[0]-xs[0])/dx));jj=int(round((p[1]-ys[0])/dy))
  if not (0<=ii<NX and 0<=jj<NY):return True
  return bool(mr[jj,ii] or mo[jj,ii])
 paths=[]
 for local in np.linspace(-1.45,1.45,15):
  c,s=np.cos(tx[2]),np.sin(tx[2]);p=np.array([tx[0]+local*c-.135*s,tx[1]+local*s+.135*c]);path=[p.copy()]
  for k in range(1900):
   e=field(p);mag=np.linalg.norm(e)
   if mag<1e-9:break
   step=.028;mid=p+e/mag*step*.5;e2=field(mid);n=np.linalg.norm(e2)
   if n<1e-9:break
   p=p+e2/n*step;path.append(p.copy())
   if is_end(p):break
   if p[1]>ys[-1]-.03 or p[1]<ys[0]+.03 or abs(p[0])>5.98:break
  path=np.asarray(path);arcs=np.r_[0,np.cumsum(np.linalg.norm(np.diff(path,axis=0),axis=1))]
  samples=np.linspace(0,arcs[-1],64)
  paths.append(np.stack([np.interp(samples,arcs,path[:,0]),np.interp(samples,arcs,path[:,1])],axis=1).round(4).tolist())
 flux=0.
 for j,i in zip(*np.nonzero(mr)):
  for dj,di,w in [(0,1,dy/dx),(0,-1,dy/dx),(1,0,dx/dy),(-1,0,dx/dy)]:
   y,x=j+dj,i+di
   if 0<=x<NX and 0<=y<NY and not mr[y,x]:flux+=V[y,x]*w
 return {'u':round(u,5),'distance':distance,'coupling':float(flux),'residual':residual,'paths':paths},V

start=time.time();morph=[];approach=[]
for i,u in enumerate(np.linspace(0,1,13)):
 state,V=solve(float(u));morph.append(state);print('morph',i,round(state['coupling'],4),flush=True)
baseline=morph[-1]['coupling']
for i,d in enumerate(np.linspace(5.6,.24,18)):
 state,V=solve(1,float(d));state['proximity']=abs(state['coupling']/baseline-1);approach.append(state);print('approach',i,round(state['proximity'],4),flush=True)
meta={'model':'2-D finite-volume Laplace, insulating finite box','grid':[NX,NY],'domain':[float(xs[0]),float(xs[-1]),float(ys[0]),float(ys[-1])],'txBias':1,'rxBias':0,'objectBias':0,'baselineCouplingArbitrary':baseline,'maxResidual':max(s['residual']for s in morph+approach),'seedCount':15,'samplesPerLine':64,'limitations':['Not a full 3-D FEM model','Grounded conductor is one representative boundary condition','No prediction of a universal sign of mutual-capacitance change','No device dimensions, absolute capacitance or measured performance implied'],'seconds':time.time()-start}
data={'metadata':meta,'morph':morph,'approach':approach}
text=json.dumps(data,separators=(',',':'))
(ROOT/'src/physics/fieldData.ts').write_text('/* Generated by scripts/physics/solve_field.py. */\nexport const fieldData = '+text+';\n')
(ROOT.parent/'qa/field-solver-report.json').write_text(json.dumps(meta,indent=2))
print('DONE',meta,flush=True)
