import {Scene,SCENES} from '../scenes/definitions.js';
import {P,ModelState,sample,analytic,wedgeValue,sectionWidth} from '../physics/model.js';
import {DATA} from '../physics/data.js';
import {Chart} from './Chart.js';
export interface Controls{next:()=>void;previous:()=>void;replay:()=>void;explore:()=>void;theta:(v:number)=>void;field:(v:string)=>void;material:()=>void;fullWidth:()=>void;go:(id:string)=>void;quality:(v:string)=>void;autoplay:()=>void;pause:()=>void;log:()=>void;}
export class HUD{
 chart:Chart;last='';copy:HTMLElement;zone:HTMLElement;mathCache=new Map<string,string>();
 constructor(public root:HTMLElement,public controls:Controls){root.innerHTML=`<header><div class="identity"><span class="identity-icon"></span><span>电容建模实验室</span></div><div class="top-actions"><button id="menu-toggle">目录 G</button><button id="explore-toggle">探索 E</button><button id="about-toggle">参数与方法</button><button id="fullscreen">全屏</button></div></header><section class="headline"><div class="part"></div><h1></h1></section><aside class="copy-panel"><div class="copy-head"><span>原理说明</span><button id="copy-toggle" aria-label="折叠说明">−</button></div><div class="copy-scroll"><div class="copy-text"></div><div class="formula"></div><p class="meaning"></p></div></aside><div id="model-zone"></div><section class="numbers"><div><span class="value-title">C₂D · 按宽度外推</span><strong id="c-value"></strong></div><div class="secondary-numbers"></div></section><div class="model-meta"></div><div class="model-controls"><button data-field="potential">电势</button><button data-field="lines">场线</button><button data-field="strength">场强</button><button id="width-toggle">全宽视图</button><button id="material-toggle">空气 / 介质</button><button id="chart-scale">纵轴对数</button></div><section class="explore-strip hidden"><label>展开角 θ <output></output><input id="theta" type="range" min="0" max="180" step=".25"></label><div class="quick-angles"><button data-angle="0">0°</button><button data-angle="30">30°</button><button data-angle="90">90°</button><button data-angle="180">180°</button></div><select id="quality"><option value="high">HIGH</option><option value="safe">SAFE</option></select></section><div class="color-legend hidden"></div><footer><span class="page-index"></span><span class="status"></span><nav><button id="prev">←</button><button id="pause">暂停 ␣</button><button id="replay">重播 R</button><button id="next">下一页 →</button><button id="autoplay">连播 P</button></nav></footer><section class="modal menu hidden"><div class="modal-title"><h2>场景目录</h2><button data-close>关闭</button></div><div class="menu-grid"></div></section><section class="modal about hidden"><div class="modal-title"><h2>同一参数源，同一物理几何</h2><button data-close>关闭</button></div><div class="about-scroll"></div></section>`;
 this.copy=root.querySelector('.copy-panel')!;this.zone=root.querySelector('#model-zone')!;this.chart=new Chart(root);
 const click=(s:string,f:()=>void)=>root.querySelector(s)!.addEventListener('click',f);click('#next',controls.next);click('#prev',controls.previous);click('#replay',controls.replay);click('#explore-toggle',controls.explore);click('#autoplay',controls.autoplay);click('#pause',controls.pause);click('#material-toggle',controls.material);click('#width-toggle',controls.fullWidth);click('#chart-scale',controls.log);click('#menu-toggle',()=>this.toggle('menu'));click('#about-toggle',()=>this.toggle('about'));click('#copy-toggle',()=>{root.classList.toggle('copy-collapsed');dispatchEvent(new Event('resize'))});click('#fullscreen',()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>{});});root.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',()=>this.close()));root.querySelectorAll<HTMLElement>('[data-field]').forEach(x=>x.addEventListener('click',()=>controls.field(x.dataset.field!)));root.querySelectorAll<HTMLElement>('[data-angle]').forEach(x=>x.addEventListener('click',()=>controls.theta(Number(x.dataset.angle))));root.querySelector('#theta')!.addEventListener('input',e=>controls.theta(Number((e.target as HTMLInputElement).value)));root.querySelector('#quality')!.addEventListener('change',e=>controls.quality((e.target as HTMLSelectElement).value));
 for(const s of SCENES){const b=document.createElement('button');b.innerHTML=`<small>${s.id}</small><span>${s.title}</span>`;b.addEventListener('click',()=>{controls.go(s.id);this.close()});root.querySelector('.menu-grid')!.append(b)}
 this.about();
 }
 math(src:string){if(!this.mathCache.has(src))this.mathCache.set(src,(globalThis as any).__vendorMath.renderToString(src,{output:'mathml',displayMode:true,throwOnError:false,strict:'ignore'}));return this.mathCache.get(src)!}
 about(){const d=P.dielectric;this.root.querySelector('.about-scroll')!.innerHTML=`<h3>真实几何与材料</h3><table><tr><td>L / b / 电极厚度</td><td>${P.length_m*1000} mm / ${P.width_m*1000} mm / ${P.electrode_thickness_m*1000} mm</td></tr><tr><td>初始净间距 D / 偏置 δ / 最终 g</td><td>${P.initial_clear_gap_m*1000} mm / ${P.hinge_offset_m*1000} mm / ${P.hinge_offset_m*2000} mm</td></tr><tr><td>激励电势差 / 空气近似</td><td>${P.voltage_difference_V} V / εair ≈ ε₀</td></tr><tr><td>真空介电常数</td><td>${P.epsilon0_F_per_m} F/m（NIST CODATA 2022）</td></tr><tr><td>固定介质</td><td>x=${d.x_start_m*1000}–${d.x_end_m*1000} mm，y=${d.y_bottom_m*1000}–${(d.y_bottom_m+d.thickness_m)*1000} mm，εr=4</td></tr></table><h3>数值基准不是实验数据</h3><p>二维无界边界元，真实有限厚度电极；${DATA.angles.length} 个角度、空气与 εr=4 两组共 ${DATA.angles.length*2} 个主求解。7 个 εr 工况在 θ=0° 独立求解。介质界面连续条件直接进入方程。</p><p>主结果是 C₂D=bC′，不忽略二维单位。完整宽度 b=120 mm；默认只显示宽度中部 ${sectionWidth*1000} mm 的几何剖切窗口，避免把薄间隙淹没在长电极中。全宽按钮显示真实完整比例，计算值不随显示模式改变。</p><p>场线是二维计算截面的三层展示，不是求解了整个三维空间。色图使用原始计算场在显示网格上的采样；这不是边界元计算网格。非角度节点采用线性插值，不冒充新求解。</p><h3>可信度与边界</h3><p>边界面元加密、独立有限体积、电荷/能量、扩大外域、εr→1、t→0 和薄共面极限均有记录。空气有限宽度 3D 仅核查 0° / 90° / 180°；介质三维端部误差未量化。所有参数为定义清楚的模型值，未声称加工、测量或材料认证。</p><h3>公式与来源</h3><p>固定转轴与局部积分由本项目重新推导。ε₀ 使用 NIST CODATA 2022；电势梯度及电介质界面条件是静电学边值问题的基本关系。具体网址、推导、求解器源码和误差数据随交付包提供。</p><p class="mono">参数 SHA-256：${DATA.parameterSha256}</p>`;}
 update(scene:Scene,s:ModelState,playing:boolean,auto:boolean,quality:string){const key=scene.id+'|'+s.explore;if(this.last!==key){this.last=key;this.root.querySelector('h1')!.textContent=scene.title;this.root.querySelector('.part')!.textContent=scene.part===1?'PART I · 几何与场模型':'PART II · 部分介质与验证';this.root.querySelector('.copy-text')!.innerHTML=scene.body;this.root.querySelector('.formula')!.innerHTML=this.math(scene.formula);this.root.querySelector('.meaning')!.textContent=scene.meaning;this.root.querySelector('.copy-scroll')!.scrollTop=0;}
 this.root.classList.toggle('exploring',s.explore);this.root.classList.toggle('no-chart',scene.chart==='none');this.root.querySelector('.explore-strip')!.classList.toggle('hidden',!s.explore);this.root.querySelector('#explore-toggle')!.textContent=s.explore?'返回演示 Esc':'探索 E';
 let activeFormula=scene.formula;
 if(scene.id==='03'&&s.phase<.32)activeFormula=String.raw`dC\approx\frac{\varepsilon b\,dx}{h(x)}`;
 else if(scene.id==='03'&&s.phase<.64)activeFormula=String.raw`\begin{aligned}h(x)&=h_0+x\tan\theta\\h_0&=\frac D2(1+\sec\theta)+\delta\tan\theta\end{aligned}`;
 else if(scene.id==='08'&&s.phase<.45)activeFormula=String.raw`\frac{1}{dC}=\frac{h-t}{\varepsilon_0 b\,dx}+\frac{t}{\varepsilon_0\varepsilon_r b\,dx}`;
 const fm=this.root.querySelector<HTMLElement>('.formula')!;if(fm.dataset.formula!==activeFormula){fm.innerHTML=this.math(activeFormula);fm.dataset.formula=activeFormula;}
 const v=sample(s.theta,s.er),w=wedgeValue(),C=scene.kind==='wedge'?w.C:v.C_F;this.root.querySelector('.value-title')!.textContent=scene.kind==='wedge'?'C扇区 · 理想边界':'C₂D · 按宽度外推';this.root.querySelector('#c-value')!.innerHTML=`${(C*1e12).toFixed(C*1e12>=10?2:3)} <small>pF</small>`;
 const an=analytic(s.theta,s.er);const norm=scene.id==='10'?v.C_F/DATA.curves['1'][0].C_F:v.C_F/DATA.curves[String(s.er===1?1:4)][0].C_F;this.root.querySelector('.secondary-numbers')!.innerHTML=scene.kind==='wedge'?`<span>内侧场强 <b>${w.Einner.toFixed(1)} V/m</b></span><span>外侧场强 <b>${w.Eouter.toFixed(1)} V/m</b></span>`:`<span>θ <b>${s.theta.toFixed(s.theta%1?2:0)}°</b> <em>εr=${s.er}</em></span><span>C′ <b>${(v.Cprime_F_per_m*1e12).toFixed(2)} pF/m</b></span><span>${scene.id==='10'?'C / C_air':'C / C₀'}<b>${norm.toFixed(3)}</b></span>`;
 const node=scene.kind==='wedge'?'严格环形扇区模型':v.exact?'当前为独立求解节点':`角度插值：${v.bracket[0]}°–${v.bracket[1]}°`;
 this.root.querySelector('.model-meta')!.innerHTML=`<span>${node}${scene.id==='09'?' · 材料附近局部场窗口':''}</span><span>${scene.kind==='wedge'?'绝缘径向边界 · 非有限极板等效':s.fullWidth?`全宽 b=${P.width_m*1000} mm · 真实比例`:`宽度中部剖切 ${sectionWidth*1000} mm · C 按全宽 ${P.width_m*1000} mm 外推`}</span>`;
 this.root.querySelector('.page-index')!.textContent=`${scene.id} / 12`;this.root.querySelector('.status')!.textContent=s.explore?'探索模式 · 拖动旋转 / 滚轮缩放':playing?'循环播放中 · 空格暂停 · → 直接下一页':'已暂停 · 空格继续 · → 直接下一页';this.root.querySelector('#pause')!.textContent=playing?'暂停 ␣':'继续 ␣';this.root.querySelector('#autoplay')!.textContent=auto?'停止连播 P':'连播 P';this.root.querySelector('#width-toggle')!.textContent=s.fullWidth?'中部剖切':'全宽视图';this.root.querySelector('#material-toggle')!.textContent=s.er>1?'改为空气':'加入 εr=4 介质';this.root.querySelector('#chart-scale')!.textContent=this.chart.log?'纵轴线性':'纵轴对数';
 this.root.querySelectorAll<HTMLElement>('[data-field]').forEach(x=>{x.classList.toggle('active',x.dataset.field===s.field);(x as HTMLButtonElement).disabled=scene.kind==='wedge'});(this.root.querySelector('#width-toggle')as HTMLButtonElement).disabled=scene.kind==='wedge';(this.root.querySelector('#material-toggle')as HTMLButtonElement).disabled=scene.kind==='wedge'||scene.id==='10';
 this.root.querySelectorAll<HTMLButtonElement>('[data-angle]').forEach(b=>b.disabled=scene.kind==='wedge'||scene.id==='10');(this.root.querySelector('#chart-scale') as HTMLButtonElement).disabled=scene.chart==='none'||scene.id==='10';const input=this.root.querySelector<HTMLInputElement>('#theta')!;input.value=String(s.theta);input.disabled=scene.kind==='wedge'||scene.id==='10';this.root.querySelector('.explore-strip output')!.textContent=s.theta.toFixed(2)+'°';(this.root.querySelector('#quality')as HTMLSelectElement).value=quality;
 const legend=this.root.querySelector<HTMLElement>('.color-legend')!;legend.classList.toggle('hidden',s.field==='lines'||s.field==='off'||scene.kind==='wedge');legend.classList.toggle('field-strength',s.field==='strength');legend.innerHTML=s.field==='strength'?'<span>|E| / V·m⁻¹</span><i></i><small>≤32　　100　　10³　　≥3.16×10³</small>':'<span>电势 / V</span><i></i><small>−0.50　　　 0　　　 +0.50</small>';
 this.chart.update(scene,s);
 }
 toggle(name:string){const target=this.root.querySelector('.'+name)!;const on=target.classList.contains('hidden');this.close();if(on)target.classList.remove('hidden')}
 close(){this.root.querySelectorAll('.modal').forEach(x=>x.classList.add('hidden'))}
 diagnostics(){const names=['.headline','.copy-panel','.numbers','.model-meta','.model-controls','.chart','.explore-strip','footer'];const rects=names.map(n=>({n,e:this.root.querySelector<HTMLElement>(n)!})).filter(x=>!x.e.classList.contains('hidden')&&getComputedStyle(x.e).display!=='none');const overflow=rects.filter(({e})=>{const r=e.getBoundingClientRect();return r.left<-.5||r.right>innerWidth+.5||r.top<-.5||r.bottom>innerHeight+.5}).map(x=>x.n);return {overflow,mathErrors:this.root.querySelectorAll('.katex-error').length,documentOverflow:document.documentElement.scrollWidth>innerWidth||document.documentElement.scrollHeight>innerHeight,rects:rects.map(({n,e})=>({name:n,rect:e.getBoundingClientRect().toJSON()}))};}
}
